version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn --bind :80 --workers 3 my_shop.wsgi
    volumes:
      - .:/shop_project
    ports:
      - "80:80"
    depends_on:
      - db