# Generated by Django 3.1.3 on 2020-11-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_ourproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurProject',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='imageproject',
            new_name='image',
        ),
    ]
